In [1]:
from galileojp.k3s import K3SGateway
from dotenv import load_dotenv
import warnings
from influxdb_client.client.warnings import MissingPivotFunction

warnings.simplefilter("ignore", MissingPivotFunction)

load_dotenv()

True

In [2]:
%env

{'PATH': '/home/silv/projects/silv-io/mulambda-experiments/.venv/bin:/home/silv/.pyenv/shims:/home/silv/.pyenv/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/home/silv/.local/share/JetBrains/Toolbox/scripts',
 'INVOCATION_ID': '87fde994fe6345b3bab86127be4b23af',
 'XAUTHORITY': '/run/user/1000/.mutter-Xwaylandauth.BRY371',
 'GDMSESSION': 'gnome',
 'XDG_DATA_DIRS': '/home/silv/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/',
 'MOTD_SHOWN': 'pam',
 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus',
 'LANG': 'en_US.UTF-8',
 'XDG_SESSION_TYPE': 'wayland',
 'XDG_ACTIVATION_TOKEN': '<hidden>',
 'PS1': '(.venv) ',
 'XDG_CURRENT_DESKTOP': 'GNOME',
 'JOURNAL_STREAM': '8:30177',
 'DISPLAY': ':0',
 'MAIL': '/var/spool/mail/silv',
 'WAYLAND_DISPLAY': 'wayland-0',
 'USERNAME': 'silv',
 'SESSION_MANAGER': 'local/io:@/tmp/.ICE-unix/2176,unix/io:/tmp/.ICE-unix/2176',
 'LOGNAME': 'silv',
 'MANAGERPID': '2008',
 'PWD': '/home/silv/projects/silv-io/mulambda-experiments',
 'XDG_SESSION_CLASS': 'user',
 'LANGUAGE': '',
 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG',
 'PYTHONPATH': '/home/silv/projects/silv-io/mulambda-experiments',
 'GDM_LANG': 'en_AT.UTF-8',
 'SHELL': '/usr/bin/zsh',
 'GIO_LAUNCHED_DESKTOP_FILE': '/usr/share/applications/pycharm-professional.desktop',
 'PYENV_ROOT': '/home/silv/.pyenv',
 'DESKTOP_SESSION': 'gnome',
 'OLDPWD': '/home/silv',
 'USER': 'silv',
 'XDG_MENU_PREFIX': 'gnome-',
 'GIO_LAUNCHED_DESKTOP_FILE_PID': '121397',
 'GJS_DEBUG_OUTPUT': 'stderr',
 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh',
 'VIRTUAL_ENV': '/home/silv/projects/silv-io/mulambda-experiments/.venv',
 'LC_ALL': 'en_US.UTF-8',
 'DEBUGINFOD_URLS': 'https://debuginfod.archlinux.org ',
 'SYSTEMD_EXEC_PID': '2196',
 'XDG_RUNTIME_DIR': '/run/user/1000',
 'GNOME_SETUP_DISPLAY': ':1',
 'XDG_SESSION_DESKTOP': 'gnome',
 'SHLVL': '0',
 'HOME': '/home/silv',
 'PYDEVD_USE_FRAME_EVAL': 'NO',
 'JPY_PARENT_PID': '207766',
 'TERM': 'xterm-color',
 'CLICOLOR': '1',
 'FORCE_COLOR': '1',
 'CLICOLOR_FORCE': '1',
 'PAGER': 'cat',
 'GIT_PAGER': 'cat',
 'MPLBACKEND': 'module://matplotlib_inline.backend_inline',
 'galileo_redis_host': 'localhost',
 'galileo_redis_password': 'o4iljt34wt89l3njr3',
 'galileo_expdb_driver': 'mixed',
 'galileo_expdb_sqlite_path': './philipp_galileo.sqlite',
 'galileo_logging_level': 'DEBUG',
 'galileo_expdb_mysql_host': 'localhost',
 'galileo_expdb_mysql_port': '3307',
 'galileo_expdb_mysql_db': 'galileo',
 'galileo_expdb_mysql_user': 'galileo',
 'galileo_expdb_mysql_password': 'galileo',
 'galileo_expdb_influxdb_url': 'http://localhost:8086',
 'galileo_expdb_influxdb_token': '<hidden>',
 'galileo_expdb_influxdb_timeout': '10000',
 'galileo_expdb_influxdb_org': 'edgerun',
 'galileo_expdb_influxdb_org_id': '2bb08062bda0d72f',
 'KUBECONFIG': '/home/silv/exp-cluster/config.yaml'}

In [3]:
gw = K3SGateway.from_env()

In [4]:
gw.experiments().sort_values(by='CREATED', ascending=False).head(10)

/home/silv/projects/silv-io/mulambda-experiments/.venv/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
/home/silv/projects/silv-io/mulambda-experiments/.venv/lib/python3.10/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,EXP_ID,NAME,CREATOR,START,END,CREATED,STATUS,metadata
11,202307211529-cf13,exp-kubejob-b96e3ebf,silvio,1.689946e+09,1.689946e+09,1.689946e+09,FINISHED,"{""exp_name"": ""kubejob"", ""exp_id"": ""20230721152..."
10,202307211501-f1c7,exp-kubejob-ce285388,silvio,1.689944e+09,1.689945e+09,1.689944e+09,FINISHED,"{""exp_name"": ""kubejob"", ""exp_id"": ""20230721150..."
9,202307211428-308b,local,silvio,1.689943e+09,1.689943e+09,1.689943e+09,FINISHED,"{""test"": ""test"", ""exp_id"": ""202307211428-308b""}"
8,202307211420-84cf,local,silvio,1.689942e+09,1.689942e+09,1.689942e+09,FINISHED,"{""test"": ""test"", ""exp_id"": ""202307211420-84cf""}"
7,202307211217-2a73,local,silvio,1.689935e+09,1.689935e+09,1.689935e+09,FINISHED,"{""test"": ""test"", ""exp_id"": ""202307211217-2a73""}"
6,202307200951-6527,test,silvio,1.689839e+09,1.689839e+09,1.689839e+09,FINISHED,"{""test"": ""test"", ""exp_id"": ""202307200951-6527""}"
5,202307200940-2320,test,silvio,1.689839e+09,1.689839e+09,1.689839e+09,FINISHED,"{""test"": ""test"", ""exp_id"": ""202307200940-2320""}"
4,202307200934-fab5,test,silvio,1.689838e+09,1.689839e+09,1.689838e+09,FINISHED,"{""test"": ""test"", ""exp_id"": ""202307200934-fab5""}"
3,202307200920-3479,test,silvio,1.689838e+09,1.689838e+09,1.689838e+09,FINISHED,"{""test"": ""test"", ""exp_id"": ""202307200920-3479""}"
2,202307130214-0821,test,silvio,1.689207e+09,1.689207e+09,1.689207e+09,FINISHED,"{""test"": ""test"", ""exp_id"": ""202307130214-0821""}"

In [5]:
exp_id = '202307211529-cf13'

In [6]:
tm = gw.telemetry(exp_id)
tm.head(10)

,value,exp_id,metric,node,ts,subsystem
ts,,,,,,
2023-07-21 13:29:18.471199512,0.505051,202307211529-cf13,cpu,m10-controller-zone-a-0,1689946158.4711995,NaN
2023-07-21 13:29:19.469614029,0.507614,202307211529-cf13,cpu,m10-controller-zone-a-0,1689946159.469614,NaN
2023-07-21 13:29:20.471142292,2.000000,202307211529-cf13,cpu,m10-controller-zone-a-0,1689946160.4711423,NaN
2023-07-21 13:29:21.470157146,4.545455,202307211529-cf13,cpu,m10-controller-zone-a-0,1689946161.4701571,NaN
2023-07-21 13:29:22.471487045,7.106599,202307211529-cf13,cpu,m10-controller-zone-a-0,1689946162.471487,NaN
2023-07-21 13:29:23.470219612,2.538071,202307211529-cf13,cpu,m10-controller-zone-a-0,1689946163.4702196,NaN
2023-07-21 13:29:24.470342159,4.522613,202307211529-cf13,cpu,m10-controller-zone-a-0,1689946164.4703422,NaN
2023-07-21 13:29:25.471524715,0.505051,202307211529-cf13,cpu,m10-controller-zone-a-0,1689946165.4715247,NaN
2023-07-21 13:29:26.470587492,2.020202,202307211529-cf13,cpu,m10-controller-zone-a-0,1689946166.4705875,NaN
2023-07-21 13:29:27.469814301,1.005025,202307211529-cf13,cpu,m10-controller-zone-a-0,1689946167.4698143,NaN

In [ ]:
ev = gw.events(exp_id)
ev.head(10)

In [ ]:
import json
from util import json_transform


copy = ev.copy()
copy['value'] = copy['value'].apply(json.loads)
transformed = json_transform(copy)
transformed

In [ ]:
transformed.plot(x='ts', y='elapsed')

In [ ]:
transformed.plot(x='ts', y='accuracy')

In [ ]:
tm[tm["metric"] == "cpu"].plot(x='ts', y='value')

In [ ]:
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter, AutoDateLocator

df = tm[tm["metric"] == "cpu"]
plt.figure(figsize=(10, 6))
plt.plot(df["ts"], df["value"])

# Format the x-axis timestamp display
date_format = DateFormatter("%b %d %H:%M")
plt.gca().xaxis.set_major_formatter(date_format)
plt.gcf().autofmt_xdate()
locator = AutoDateLocator(maxticks=5)
plt.gca().xaxis.set_major_locator(locator)

plt.xlabel("Time")
plt.ylabel("CPU")
plt.grid(True)
plt.show()